import type { Metadata } from "next";
import "./globals.css";
import { RootLayoutClient } from "./layout.client";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getSession({''});
  // console.log('@root layout session', session);
  const session = await getServerSession(authOptions);
  console.log('root layout session', session);

  return (
    <html lang="ko">
      <body>
        <RootLayoutClient session={session}>
          { children }
        </RootLayoutClient>
      </body>
    </html>
  );
}
